import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const ROOT=path.resolve('public'), rooms=new Map();
const C={Animals:['ant','ape','alligator','bear','bee','buffalo','cat','camel','cheetah','chicken','cow','crab','deer','dog','dolphin','donkey','eagle','elephant','fox','frog','giraffe','goat','gorilla','horse','jaguar','kangaroo','koala','lion','monkey','mouse','otter','panda','parrot','penguin','rabbit','rat','shark','sheep','snake','spider','squirrel','tiger','turtle','wolf','zebra'],Food:['apple','banana','burger','bread','cake','carrot','cheese','chicken','coconut','cookie','curry','donut','egg','fries','garlic','grape','guava','honey','kiwi','lemon','mango','melon','noodles','orange','pasta','pear','pizza','potato','rice','salad','samosa','spinach','strawberry','taco','tomato','waffle','watermelon'],Countries:['argentina','australia','austria','bangladesh','belgium','brazil','canada','chile','china','colombia','croatia','denmark','egypt','ethiopia','finland','france','germany','ghana','greece','india','indonesia','ireland','italy','japan','kenya','malaysia','mexico','nepal','netherlands','nigeria','norway','pakistan','peru','poland','portugal','qatar','romania','russia','singapore','spain','sweden','switzerland','thailand','turkey','ukraine','vietnam'],Sports:['archery','athletics','badminton','baseball','basketball','boxing','cricket','cycling','football','golf','hockey','judo','karate','rowing','rugby','skiing','soccer','surfing','swimming','tennis','volleyball','wrestling'],Jobs:['actor','artist','baker','barber','chef','dentist','doctor','driver','engineer','farmer','firefighter','guard','judge','lawyer','manager','mechanic','nurse','pilot','plumber','police','programmer','singer','teacher','waiter','writer'],Movies:['avatar','alien','batman','coco','dune','frozen','gladiator','inception','interstellar','jaws','joker','matrix','moana','rocky','shrek','titanic','up']};
const letters='ABCDEFGHIJKLMNOPQRSTUVW'.split(''), specials=['grid','risk','lastChance'];
const norm=s=>String(s??'').trim().toLowerCase().replace(/[^a-z0-9]/g,'');
const valid=(a,c,l)=>{const n=norm(a);return !!n&&n.startsWith(l.toLowerCase())&&(C[c]||[]).includes(n)};
const pick=a=>a[Math.floor(Math.random()*a.length)]; const rid=()=>crypto.randomBytes(2).toString('hex').toUpperCase(); const pid=()=>crypto.randomUUID();
function roomView(r){return {code:r.code,hostId:r.hostId,rounds:r.totalRounds,round:r.round,phase:r.phase,kind:r.kind,category:r.category,letter:r.letter,endsAt:r.endsAt,version:r.version,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:p.score,connected:p.connected,host:p.id===r.hostId,challenged:!!p.challenged,answered:p.phase==='results'?!!p.answer:(p.answer?true:undefined),answer:r.phase==='results'?p.answer?.value||'':undefined,valid:r.phase==='results'?!!p.answer?.valid:undefined}))}}
function push(r){r.version++;r.lastActive=Date.now()}
function choosePrompt(){return {category:pick(Object.keys(C)),letter:pick(letters)}};
function ensureHost(r){if(r.hostId){const h=r.players.get(r.hostId);if(h&&h.connected)return}const next=[...r.players.values()].find(p=>p.connected)||[...r.players.values()][0];if(next)r.hostId=next.id}
function startRound(r){if(r.round>r.totalRounds)return endGame(r);r.phase='playing';r.kind=(r.round>1&&Math.random()<.22)?pick(specials):'normal';const q=choosePrompt();r.category=q.category;r.letter=q.letter;r.endsAt=Date.now()+(r.kind==='grid'?35000:20000);for(const p of r.players.values()){p.answer=null;p.grid={};p.risk=false;p.challenged=false}push(r);setTimeout(()=>{if(r.phase==='playing')finishRound(r)},(r.endsAt-Date.now())+100)}
function finishRound(r){if(r.phase!=='playing')return;r.phase='results';const ps=[...r.players.values()];if(r.kind==='normal'||r.kind==='risk'){const counts=new Map();ps.forEach(p=>{if(p.answer?.valid)counts.set(p.answer.value,(counts.get(p.answer.value)||0)+1)});ps.forEach(p=>{if(p.answer?.valid)p.score+=r.kind==='risk'?(p.risk?4:2):(counts.get(p.answer.value)===1?2:1)})}else if(r.kind==='grid'){const counts=new Map();ps.forEach(p=>Object.values(p.grid).forEach(a=>{if(a.valid)counts.set(a.value,(counts.get(a.value)||0)+1)}));ps.forEach(p=>Object.values(p.grid).forEach(a=>{if(a.valid)p.score+=counts.get(a.value)===1?2:1}))}else if(r.kind==='lastChance'){ps.forEach(p=>{if(p.answer?.valid)p.score+=1})}push(r);setTimeout(()=>{if(r.phase!=='results')return;r.round++;startRound(r)},2500)}
function endGame(r){const ps=[...r.players.values()],max=Math.max(...ps.map(p=>p.score)),ties=ps.filter(p=>p.score===max);if(ties.length>1)return sudden(r,ties.map(p=>p.id));r.phase='finished';r.winner=ties[0].id;push(r)}
function sudden(r,ids){const q=choosePrompt();r.phase='sudden';r.tieIds=ids;r.kind='sudden';r.category=q.category;r.letter=q.letter;r.endsAt=Date.now()+20000;for(const p of r.players.values()){p.answer=null;p.challenged=false}push(r);setTimeout(()=>resolveSudden(r),20100)}
function resolveSudden(r){if(r.phase!=='sudden')return;const ties=r.tieIds.map(id=>r.players.get(id)).filter(Boolean);const validOnes=ties.filter(p=>p.answer?.valid);if(validOnes.length===1){r.phase='finished';r.winner=validOnes[0].id;push(r)}else{const q=choosePrompt();r.category=q.category;r.letter=q.letter;r.endsAt=Date.now()+20000;ties.forEach(p=>{p.answer=null;p.challenged=false});push(r);setTimeout(()=>resolveSudden(r),20100)}}
function create(){let c;do{c=rid()}while(rooms.has(c));const r={code:c,hostId:null,players:new Map(),totalRounds:8,round:0,phase:'lobby',version:0,lastActive:Date.now(),createdAt:Date.now()};rooms.set(c,r);return r}
function body(req){return new Promise((res,rej)=>{let b='';req.on('data',x=>{b+=x;if(b.length>1e4){rej(new Error('too big'));req.destroy()}});req.on('end',()=>{try{res(JSON.parse(b||'{}'))}catch(e){rej(e)}})})}
function json(res,obj,status=200){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'});res.end(JSON.stringify(obj))}
function handle(req,res){const u=new URL(req.url,'http://localhost');if(req.method==='GET'){if(u.pathname==='/api/state'){const r=rooms.get(u.searchParams.get('code'));const viewer=u.searchParams.get('playerId');if(r&&viewer&&r.players.has(viewer)){const p=r.players.get(viewer);p.lastSeen=Date.now();if(!p.connected){p.connected=true;push(r)}}return json(res,r?{ok:true,version:r.version,room:roomView(r)}:{ok:false})}let f=path.join(ROOT,u.pathname==='/'?'index.html':u.pathname.slice(1));if(!f.startsWith(ROOT))return json(res,{error:'bad path'},400);if(fs.existsSync(f)){const ext=path.extname(f),types={'.html':'text/html','.js':'text/javascript','.css':'text/css'};res.writeHead(200,{'content-type':types[ext]||'application/octet-stream','cache-control':'no-store'});return fs.createReadStream(f).pipe(res)}return json(res,{error:'not found'},404)}
if(req.method!=='POST')return json(res,{error:'method'},405);body(req).then(m=>{const action=u.pathname.slice(5);if(action==='create'){const r=create(),p={id:pid(),name:String(m.name||'Player').slice(0,20),score:0,connected:true,lastSeen:Date.now(),answer:null,grid:{},challenged:false};r.hostId=p.id;r.players.set(p.id,p);push(r);return json(res,{ok:true,you:p.id,room:roomView(r)})}
if(action==='join'){const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return json(res,{error:'Room not found.'},404);if(r.phase!=='lobby')return json(res,{error:'Game already started; late joining is closed.'},400);if(r.players.size>=8)return json(res,{error:'Room is full.'},400);const p={id:pid(),name:String(m.name||'Player').slice(0,20),score:0,connected:true,lastSeen:Date.now(),answer:null,grid:{},challenged:false};r.players.set(p.id,p);push(r);return json(res,{ok:true,you:p.id,room:roomView(r)})}
const r=rooms.get(String(m.code||'').toUpperCase());if(!r)return json(res,{error:'Room not found.'},404);const p=r.players.get(m.playerId);if(!p)return json(res,{error:'Player not found.'},404);p.lastSeen=Date.now();if(!p.connected){p.connected=true;push(r)}r.lastActive=Date.now();
if(action==='setRounds'){if(r.phase!=='lobby')return json(res,{error:'Game already started.'},400);if(r.hostId!==p.id)return json(res,{error:'Only the host can change rounds.'},403);if(![5,8,10].includes(+m.rounds))return json(res,{error:'Invalid rounds.'},400);r.totalRounds=+m.rounds;push(r);return json(res,{ok:true})}
if(action==='start'){if(r.phase!=='lobby')return json(res,{error:'Game already started.'},400);if(r.hostId!==p.id)return json(res,{error:'Only the host can start the game.'},403);if(r.players.size<2)return json(res,{error:'Need at least 2 players to start.'},400);r.round=1;startRound(r);return json(res,{ok:true})}
if(action==='answer'){if(!['playing','sudden'].includes(r.phase))return json(res,{error:'No round is active.'},400);if(p.answer)return json(res,{ok:true});const value=String(m.answer||'').slice(0,50);p.answer={value:norm(value),valid:valid(value,r.category,r.letter)};p.risk=!!m.risk;push(r);if(r.phase==='sudden'&&r.tieIds.every(id=>r.players.get(id)?.answer))resolveSudden(r);return json(res,{ok:true})}
if(action==='grid'){if(r.phase!=='playing'||r.kind!=='grid')return json(res,{error:'Not a grid round.'},400);const cat=String(m.category||'');if(!['Animals','Food','Countries'].includes(cat))return json(res,{error:'bad category'},400);if(p.grid[cat])return json(res,{ok:true});const value=String(m.answer||'').slice(0,50);p.grid[cat]={value:norm(value),valid:valid(value,cat,r.letter)};push(r);return json(res,{ok:true})}
if(action==='challenge'){if(r.phase!=='results')return json(res,{error:'Challenges are only open during results.'},400);const target=r.players.get(String(m.targetId));if(!target||target.id===p.id)return json(res,{error:'Cannot challenge that player.'},400);if(!target.answer)return json(res,{error:'That player did not answer.'},400);if(p.challenged)return json(res,{error:'You already challenged this round.'},400);p.challenged=true;if(target.answer.valid){p.score=Math.max(0,p.score-1);target.score+=1}else{p.score+=1}push(r);return json(res,{ok:true})}
if(action==='reconnect'){p.connected=true;push(r);return json(res,{ok:true})}
return json(res,{error:'bad action'},400)}).catch(()=>json(res,{error:'bad json'},400))}
const server=http.createServer(handle);server.listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('Word Battle: http://localhost:'+(process.env.PORT||3000)));
setInterval(()=>{const now=Date.now();for(const r of rooms.values()){let changed=false;for(const p of r.players.values()){if(p.connected&&p.lastSeen&&now-p.lastSeen>8000){p.connected=false;changed=true}}if(changed){ensureHost(r);push(r)}if(now-r.lastActive>30*60*1000)rooms.delete(r.code)}},2000);
